/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as CinemasRouteImport } from './routes/cinemas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReserverCinemaIdRouteImport } from './routes/reserver.$cinemaId'
import { Route as MoviesIdRouteImport } from './routes/movies.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemasRoute = CinemasRouteImport.update({
  id: '/cinemas',
  path: '/cinemas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverCinemaIdRoute = ReserverCinemaIdRouteImport.update({
  id: '/reserver/$cinemaId',
  path: '/reserver/$cinemaId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MoviesRoute,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/movies': typeof MoviesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/book/$id': typeof BookIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reserver/$cinemaId': typeof ReserverCinemaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/movies': typeof MoviesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/book/$id': typeof BookIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reserver/$cinemaId': typeof ReserverCinemaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/movies': typeof MoviesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/book/$id': typeof BookIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/reserver/$cinemaId': typeof ReserverCinemaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/movies'
    | '/sitemap.xml'
    | '/tickets'
    | '/book/$id'
    | '/movies/$id'
    | '/reserver/$cinemaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/movies'
    | '/sitemap.xml'
    | '/tickets'
    | '/book/$id'
    | '/movies/$id'
    | '/reserver/$cinemaId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/movies'
    | '/sitemap.xml'
    | '/tickets'
    | '/book/$id'
    | '/movies/$id'
    | '/reserver/$cinemaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CinemasRoute: typeof CinemasRoute
  MoviesRoute: typeof MoviesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TicketsRoute: typeof TicketsRoute
  BookIdRoute: typeof BookIdRoute
  ReserverCinemaIdRoute: typeof ReserverCinemaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinemas': {
      id: '/cinemas'
      path: '/cinemas'
      fullPath: '/cinemas'
      preLoaderRoute: typeof CinemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$cinemaId': {
      id: '/reserver/$cinemaId'
      path: '/reserver/$cinemaId'
      fullPath: '/reserver/$cinemaId'
      preLoaderRoute: typeof ReserverCinemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoviesRouteChildren {
  MoviesIdRoute: typeof MoviesIdRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesIdRoute: MoviesIdRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CinemasRoute: CinemasRoute,
  MoviesRoute: MoviesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TicketsRoute: TicketsRoute,
  BookIdRoute: BookIdRoute,
  ReserverCinemaIdRoute: ReserverCinemaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
